sudo: false
language: rust
rust:
- 1.38.0 # rust-ffmpeg-sys supports up to this.
matrix:
  allow_failures:
  - rust: nightly
addons:
  apt:
    packages:
    - libgl1-mesa-dev:i386
    - gcc-multilib
    - yasm
    - zlib1g-dev:i386
env:
  global:
  - RUST_BACKTRACE=1
  - PKG_CONFIG_ALLOW_CROSS=1
cache:
  cargo: true
  directories:
  - "$HOME/ffmpeg"
  - "$HOME/SDL2"
  - "$HOME/OpenCL"
before_install:
- bash .travis/install-ffmpeg.sh
- ls -R "$HOME/ffmpeg"
- bash .travis/install-sdl2.sh
- ls -R "$HOME/SDL2"
- bash .travis/install-opencl.sh
- ls -R "$HOME/OpenCL"
- export PKG_CONFIG_PATH="$HOME/ffmpeg/lib/pkgconfig:$HOME/SDL2/lib/pkgconfig"
- export LD_LIBRARY_PATH="$HOME/ffmpeg/lib"
install:
- rustup target add i686-unknown-linux-gnu
script:
- mkdir -p target/i686-unknown-linux-gnu/debug/deps
- cp $HOME/OpenCL/lib/libOpenCL.so* target/i686-unknown-linux-gnu/debug/deps/
- cargo build --verbose
- if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
    cargo doc --no-deps --document-private-items;
    cp .travis/index.html target/i686-unknown-linux-gnu/doc;
  fi
- cargo test --verbose
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: target/i686-unknown-linux-gnu/doc
  on:
    branch: master
    rust: stable
