[package]
name = "hl-capture"
version = "0.1.0"
authors = ["Ivan Molodetskikh <yalterz@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
error-chain = "0.10"
ffmpeg-sys = "3.2.1"
lazy_static = "0.2"
libc = "0.2"
